# Generated by Django 6.0.2 on 2026-03-04 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_comment='코드 값', max_length=10)),
                ('group_code', models.CharField(db_comment='그룹 코드', max_length=10)),
                ('name', models.CharField(db_comment='코드명', max_length=100)),
                ('order', models.PositiveIntegerField(db_comment='정렬 순서', default=0)),
                ('code_descipt', models.CharField(db_comment='코드 설명', max_length=200)),
                ('use_yn', models.BooleanField(db_comment='사용 여부', default=True)),
                ('reg_dt', models.DateTimeField(auto_now_add=True, db_comment='등록일시')),
                ('mod_dt', models.DateTimeField(auto_now=True, db_comment='수정일시')),
            ],
            options={
                'db_table': 'tb_code',
                'ordering': ['group_code', 'order'],
                'unique_together': {('group_code', 'code')},
            },
        ),
    ]
