# Generated by Django 6.0.2 on 2026-03-04 06:23

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_comment='기관명', max_length=100)),
                ('org_type', models.CharField(choices=[('OG01', '한국교육과정평가원'), ('OG02', '표집학교'), ('OG03', '교육부'), ('OG04', '시도교육청')], db_comment='기관유형', max_length=10)),
                ('reg_dt', models.DateTimeField(auto_now_add=True, db_comment='등록일시')),
                ('mod_dt', models.DateTimeField(auto_now=True, db_comment='수정일시')),
            ],
            options={
                'db_table': 'tb_organization',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('auth_type', models.CharField(choices=[('AT01', '사이트관리자'), ('AT02', '모든권한'), ('AT03', '업무담당자'), ('AT04', '감독교사'), ('AT05', 'ICT담당자')], db_comment='사용자 권한', max_length=20)),
                ('account_id', models.CharField(db_comment='사용자 계정', max_length=20, unique=True)),
                ('viewing_day', models.JSONField(blank=True, db_comment='시청 가능 일자', default=list, validators=[user.models.validate_weekdays])),
                ('name', models.CharField(blank=True, db_comment='사용자 이름', max_length=50)),
                ('reg_dt', models.DateTimeField(auto_now_add=True, db_comment='등록일시')),
                ('mod_dt', models.DateTimeField(auto_now=True, db_comment='수정일시')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('organization', models.ForeignKey(blank=True, db_comment='소속 기관', null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.organization')),
            ],
            options={
                'db_table': 'tb_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
