# Generated by Django 6.0.2 on 2026-03-05 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='use_yn',
            field=models.BooleanField(db_comment='사용 여부', default=True),
        ),
    ]
