# Generated by Django 6.0.2 on 2026-03-04 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_role', models.CharField(choices=[('AT03', '업무담당자'), ('AT04', '감독교사'), ('AT05', 'ICT담당자')], db_comment='시청 가능 역할', max_length=10)),
                ('order', models.PositiveIntegerField(db_comment='차시 순서')),
                ('title', models.CharField(db_comment='프로그램명', max_length=200)),
                ('reg_dt', models.DateTimeField(auto_now_add=True, db_comment='등록일시')),
                ('mod_dt', models.DateTimeField(auto_now=True, db_comment='수정일시')),
            ],
            options={
                'db_table': 'tb_program',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(db_comment='파일 경로', max_length=200)),
                ('origin_file_name', models.CharField(db_comment='원본 파일명', max_length=200)),
                ('service_file_name', models.CharField(db_comment='서비스 파일명', max_length=200)),
                ('ext', models.CharField(db_comment='파일 확장자', max_length=20)),
                ('title', models.CharField(db_comment='차시명(프로그램 명)', max_length=200)),
                ('duration', models.PositiveIntegerField(db_comment='총 길이 (초)')),
                ('file_size', models.BigIntegerField(db_comment='파일 크기')),
                ('reg_dt', models.DateTimeField(auto_now_add=True, db_comment='등록일시')),
                ('mod_dt', models.DateTimeField(auto_now=True, db_comment='수정일시')),
                ('program', models.ForeignKey(db_comment='프로그램 FK', null=True, on_delete=django.db.models.deletion.CASCADE, to='video.program')),
            ],
            options={
                'db_table': 'tb_video',
            },
        ),
        migrations.CreateModel(
            name='VideoProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_position', models.PositiveIntegerField(db_comment='마지막 재생 위치(초)', default=0)),
                ('watched_section', models.JSONField(db_comment='실제 시청 누적 시간 SET 정보', default=list)),
                ('is_completed', models.BooleanField(db_comment='이수 완료 여부', default=False)),
                ('completed_at', models.DateTimeField(blank=True, db_comment='이수 완료 일시', null=True)),
                ('reg_dt', models.DateTimeField(auto_now_add=True, db_comment='등록일시')),
                ('mod_dt', models.DateTimeField(auto_now=True, db_comment='수정일시')),
                ('user', models.ForeignKey(db_comment='사용자ID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(db_comment='영상ID', on_delete=django.db.models.deletion.CASCADE, to='video.video')),
            ],
            options={
                'db_table': 'tb_video_progress',
                'unique_together': {('user', 'video')},
            },
        ),
    ]
