# Generated by Django 6.0.2 on 2026-03-04 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='service_file_name',
        ),
        migrations.AddField(
            model_name='program',
            name='use_yn',
            field=models.BooleanField(db_comment='사용 여부', default=True),
        ),
        migrations.AddField(
            model_name='video',
            name='server_file_name',
            field=models.CharField(db_comment='서버 파일명', default='', max_length=200),
        ),
        migrations.AddField(
            model_name='video',
            name='use_yn',
            field=models.BooleanField(db_comment='사용 여부', default=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='origin_file_name',
            field=models.CharField(db_comment='원본 파일명', default='', max_length=200),
        ),
    ]
