# Generated by Django 6.0.2 on 2026-03-05 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_remove_video_service_file_name_program_use_yn_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='title',
        ),
    ]
